# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kyber < Formula
  desc "A function-level Go code-quality analyzer — cyclomatic complexity, testability, readability, and more."
  homepage "https://github.com/jedi-knights/kyber"
  version "0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/kyber/releases/download/v0/kyber_0_darwin_amd64.tar.gz"
      sha256 "d3be2fc4adb57dbd754512d76fb2d29e8f1dbffdbc8a9b36a44a95c38ce7643e"

      define_method(:install) do
        bin.install "kyber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/kyber/releases/download/v0/kyber_0_darwin_arm64.tar.gz"
      sha256 "3d41e9251e9dd44a91ee42725a2fc3cfdc2e54a365b22e7059b13f9eafe72c7e"

      define_method(:install) do
        bin.install "kyber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/kyber/releases/download/v0/kyber_0_linux_amd64.tar.gz"
      sha256 "caddb6fefd9812baedbe545570fc8fab910027db125db4cc0eaad477f229886b"
      define_method(:install) do
        bin.install "kyber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/kyber/releases/download/v0/kyber_0_linux_arm64.tar.gz"
      sha256 "b06046cae1f5cb3fa6648e8375640a1ece7de513f0d2c634c4861c1bd4ad3975"
      define_method(:install) do
        bin.install "kyber"
      end
    end
  end

  test do
    system "#{bin}/kyber", "version"
  end
end
