# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kyber < Formula
  desc "A function-level Go code-quality analyzer — cyclomatic complexity, testability, readability, and more."
  homepage "https://github.com/jedi-knights/kyber"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/kyber/releases/download/v0.5.0/kyber_0.5.0_darwin_amd64.tar.gz"
      sha256 "71bd8501b1244b864763d3f76a7f1df929e838913cb40365b11e4c22474570a2"

      define_method(:install) do
        bin.install "kyber"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/kyber/releases/download/v0.5.0/kyber_0.5.0_darwin_arm64.tar.gz"
      sha256 "673a2b67fdf54fab2b80872e97340ac0173e2065c10bc5f6bb118ee7b5a58733"

      define_method(:install) do
        bin.install "kyber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/kyber/releases/download/v0.5.0/kyber_0.5.0_linux_amd64.tar.gz"
      sha256 "0e7f0418e3ff6002496eca8ebb923f426a0b3c45c517f743b9c54552e6263177"
      define_method(:install) do
        bin.install "kyber"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/kyber/releases/download/v0.5.0/kyber_0.5.0_linux_arm64.tar.gz"
      sha256 "72bbf0038d13b5b3ce69ea56d6ac4efaf3f5988d927194a6c4e9237ef62ca212"
      define_method(:install) do
        bin.install "kyber"
      end
    end
  end

  test do
    system "#{bin}/kyber", "version"
  end
end
