# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lexicon < Formula
  desc "A markdown-native requirements DSL, translatable to Gherkin, Gauge, and beyond."
  homepage "https://github.com/jedi-knights/lexicon"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.1.0/lexicon_0.1.0_darwin_amd64.tar.gz"
      sha256 "672a3fe584f51452032bcfdb8521ca4ff83c202c37bcb74de33c892c5ae831a3"

      define_method(:install) do
        bin.install "lexicon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.1.0/lexicon_0.1.0_darwin_arm64.tar.gz"
      sha256 "c28ed7f05c04d83350d553ee3c98def678c2611f4b4b52b1e1ebea047cf05b15"

      define_method(:install) do
        bin.install "lexicon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.1.0/lexicon_0.1.0_linux_amd64.tar.gz"
      sha256 "f0b6a79fd74a0e5a0b6c99967be89f18dea5a30ecfa8b7519cf1ebd0d6845b2d"
      define_method(:install) do
        bin.install "lexicon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.1.0/lexicon_0.1.0_linux_arm64.tar.gz"
      sha256 "1268a4b232358f0f29455ca17f8433ddc517a3100b8424feec8644fcad58c23b"
      define_method(:install) do
        bin.install "lexicon"
      end
    end
  end

  test do
    system "#{bin}/lexicon", "version"
  end
end
