# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lexicon < Formula
  desc "A markdown-native requirements DSL, translatable to Gherkin, Gauge, and beyond."
  homepage "https://github.com/jedi-knights/lexicon"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.4.0/lexicon_0.4.0_darwin_amd64.tar.gz"
      sha256 "39c4416572a84fde9ea96ef27c96f248d8f51e8b0782192e84e0f883b5676da7"

      define_method(:install) do
        bin.install "lexicon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.4.0/lexicon_0.4.0_darwin_arm64.tar.gz"
      sha256 "3a7341e0bdabab0548b83059ce714df74b8c2335d49d918fd6466f4e16260aab"

      define_method(:install) do
        bin.install "lexicon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.4.0/lexicon_0.4.0_linux_amd64.tar.gz"
      sha256 "2aaa816092f8ef5d173e9607c54df0a105c10137429ca4f1714f9d2774bc0d54"
      define_method(:install) do
        bin.install "lexicon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.4.0/lexicon_0.4.0_linux_arm64.tar.gz"
      sha256 "a8b59c6eaa688e5ea225153f099c8fe2a1c1175ebc684e46428391dc07287aca"
      define_method(:install) do
        bin.install "lexicon"
      end
    end
  end

  test do
    system "#{bin}/lexicon", "version"
  end
end
