# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lexicon < Formula
  desc "A markdown-native requirements DSL, translatable to Gherkin, Gauge, and beyond."
  homepage "https://github.com/jedi-knights/lexicon"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.2.0/lexicon_0.2.0_darwin_amd64.tar.gz"
      sha256 "b11ba5e0b3ddc4503419f918c2db941e6c6d3153af42a688306edc7cf0d5e487"

      define_method(:install) do
        bin.install "lexicon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.2.0/lexicon_0.2.0_darwin_arm64.tar.gz"
      sha256 "7c087f83a3af8589e6f4d358150889ee4243b8392365916e1832db39053d5265"

      define_method(:install) do
        bin.install "lexicon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.2.0/lexicon_0.2.0_linux_amd64.tar.gz"
      sha256 "2f1f177f2403871d8ecb86b388d86aacbb3b094d763eacf523368c9e3f3ee8f6"
      define_method(:install) do
        bin.install "lexicon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/lexicon/releases/download/v0.2.0/lexicon_0.2.0_linux_arm64.tar.gz"
      sha256 "566aa757abe12b8bd17fbcf34f1c5a7acb770d6cd87a16df17b31c6854c0905f"
      define_method(:install) do
        bin.install "lexicon"
      end
    end
  end

  test do
    system "#{bin}/lexicon", "version"
  end
end
