# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neospec < Formula
  desc "A self-contained test runner and coverage tool for Neovim plugins and distributions."
  homepage "https://github.com/jedi-knights/neospec"
  version "0.22.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.22.0/neospec_0.22.0_darwin_amd64.tar.gz"
      sha256 "3f5ac1ccc71d3c2dffd93a3d2bcf8baf3206b341e39f6667e54b52beb38c11e0"

      define_method(:install) do
        bin.install "neospec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.22.0/neospec_0.22.0_darwin_arm64.tar.gz"
      sha256 "a1ad3a9712e32bf79ac8f2f49b8d35e0b83dc36c6cd4f5d5e57e0aafbcfcdea2"

      define_method(:install) do
        bin.install "neospec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.22.0/neospec_0.22.0_linux_amd64.tar.gz"
      sha256 "085c2075759030d40590144047e73abe1cba17ae1f920bea0c30f55878557ecd"
      define_method(:install) do
        bin.install "neospec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.22.0/neospec_0.22.0_linux_arm64.tar.gz"
      sha256 "7ea87ec7e8de460de98666e5b9f515a9a0f9fea415f743b6061f317c5864deff"
      define_method(:install) do
        bin.install "neospec"
      end
    end
  end

  test do
    system "#{bin}/neospec", "version"
  end
end
