# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neospec < Formula
  desc "A self-contained test runner and coverage tool for Neovim plugins and distributions."
  homepage "https://github.com/jedi-knights/neospec"
  version "0.23.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.23.0/neospec_0.23.0_darwin_amd64.tar.gz"
      sha256 "eee8fa0e8091a6ae2c2fdc2f14c391304a3b9eb10d0b5715d715784023dbc4e7"

      define_method(:install) do
        bin.install "neospec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.23.0/neospec_0.23.0_darwin_arm64.tar.gz"
      sha256 "0d93f5ae4f9be587a4876afa57945e92dea8f15507f64fbd2582172875f0974d"

      define_method(:install) do
        bin.install "neospec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.23.0/neospec_0.23.0_linux_amd64.tar.gz"
      sha256 "f7ba0708a6a64133c5069a6cc6e1c497af18d2c2a3d8d4018c16ac3218e3d83c"
      define_method(:install) do
        bin.install "neospec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.23.0/neospec_0.23.0_linux_arm64.tar.gz"
      sha256 "a49c5010634993f11f00f1e3404fc1ab549959653d32522f92184e14164dec0d"
      define_method(:install) do
        bin.install "neospec"
      end
    end
  end

  test do
    system "#{bin}/neospec", "version"
  end
end
