# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neospec < Formula
  desc "A self-contained test runner and coverage tool for Neovim plugins and distributions."
  homepage "https://github.com/jedi-knights/neospec"
  version "0.24.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.24.0/neospec_0.24.0_darwin_amd64.tar.gz"
      sha256 "2f290e4258f6618afd5f698f4f92e84ee9a1541de30a982b2dad69602a52e875"

      define_method(:install) do
        bin.install "neospec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.24.0/neospec_0.24.0_darwin_arm64.tar.gz"
      sha256 "0c20abcc01ac4705bfbfc1f0ab3d0e3ae83f57cdd5877c965bad5e8d3846a0ab"

      define_method(:install) do
        bin.install "neospec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.24.0/neospec_0.24.0_linux_amd64.tar.gz"
      sha256 "82be1e451e451ac30c6d77c5ebbb2c5f83932e7c553f0e7026422dad3910a199"
      define_method(:install) do
        bin.install "neospec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/neospec/releases/download/v0.24.0/neospec_0.24.0_linux_arm64.tar.gz"
      sha256 "45e88403256218084bd1c2c85cc6b598ee170c9ee8e4565d25a4acc2ceed71ee"
      define_method(:install) do
        bin.install "neospec"
      end
    end
  end

  test do
    system "#{bin}/neospec", "version"
  end
end
