# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlugScaffold < Formula
  desc "Neovim plugin project generator"
  homepage "https://github.com/jedi-knights/plug-scaffold"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.0/plug-scaffold_0.2.0_darwin_amd64.tar.gz"
      sha256 "8fda1b09b9d7c3a9eb16989f3e2b83ad7c19a909b55f97e491c4336d1f1791d4"

      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.0/plug-scaffold_0.2.0_darwin_arm64.tar.gz"
      sha256 "e0f5c32690f301021d5a6abf359ed65f0a81c75d48169a25e049e6d28a3e39de"

      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.0/plug-scaffold_0.2.0_linux_amd64.tar.gz"
      sha256 "9bae18b061031c3b2e43bc854934734caf9789cba492492de2d33195e0ea2a4e"
      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.0/plug-scaffold_0.2.0_linux_arm64.tar.gz"
      sha256 "8edb628beddf5752416a3c087b8432bc5d6d6d6d176f45d8b0479955406c2a45"
      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
  end

  test do
    system "#{bin}/plug-scaffold", "version"
  end
end
