# typed: false
# frozen_string_literal: true

# Hand-written formula for plug-audit v0.1.0 (cargo-dist tarballs).
# Later releases can be auto-generated by cargo-dist's homebrew
# installer — see the plug-audit repo's dist-workspace.toml.
class PlugAudit < Formula
  desc "Static analyzer for Neovim plugin repos"
  homepage "https://github.com/jedi-knights/plug-audit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/plug-audit/releases/download/v0.1.0/plug-audit-x86_64-apple-darwin.tar.xz"
      sha256 "309f3e9a614fbebcfb9c84978251aed75e213517374830005f38933134efe2e7"

      define_method(:install) do
        bin.install "plug-audit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/plug-audit/releases/download/v0.1.0/plug-audit-aarch64-apple-darwin.tar.xz"
      sha256 "f8564905a36c231d3ce2f0bd82d9c552d61366a613d5fdce7ab1888747be97d2"

      define_method(:install) do
        bin.install "plug-audit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/plug-audit/releases/download/v0.1.0/plug-audit-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "748807a3008abc06cc07da635b14b13382812bd2b74ad7830e7e852ccb90d6fb"

      define_method(:install) do
        bin.install "plug-audit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/plug-audit/releases/download/v0.1.0/plug-audit-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "e7de2d59e2b5690414db0d7a505ef8dcc5d5cb9c6321b366a53878a9828dd62c"

      define_method(:install) do
        bin.install "plug-audit"
      end
    end
  end

  test do
    system "#{bin}/plug-audit", "--version"
  end
end
