# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PlugScaffold < Formula
  desc "Neovim plugin project generator"
  homepage "https://github.com/jedi-knights/plug-scaffold"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.1/plug-scaffold_0.2.1_darwin_amd64.tar.gz"
      sha256 "b37e158608a450cce8c4547ee65c1221e85f61205a19fe5e4f915ca6cfe2e526"

      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.1/plug-scaffold_0.2.1_darwin_arm64.tar.gz"
      sha256 "7fc4e1c41af5fcdb0b5925a494a5cb2506de276f409647bb17802a21a350b3d2"

      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.1/plug-scaffold_0.2.1_linux_amd64.tar.gz"
      sha256 "ebe9d6c3f02ca6a01f457677561db39bc809e7eaefab67ada531ab1d9e467726"
      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/plug-scaffold/releases/download/v0.2.1/plug-scaffold_0.2.1_linux_arm64.tar.gz"
      sha256 "21d127719cf91d6de9e1ab80c15bc68798e3390aa66ed972863b1e1beaa7dc3e"
      define_method(:install) do
        bin.install "plug-scaffold"
      end
    end
  end

  test do
    system "#{bin}/plug-scaffold", "version"
  end
end
