# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Repo < Formula
  desc "Demo CLI over the repometa library for scanning source repositories."
  homepage "https://github.com/jedi-knights/repo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/repo/releases/download/v0.1.0/repo_0.1.0_darwin_amd64.tar.gz"
      sha256 "6e21f4b11c637d5c41e063378588d9076df11fbb016c0c7147091bfbe97e3a3b"

      define_method(:install) do
        bin.install "repo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/repo/releases/download/v0.1.0/repo_0.1.0_darwin_arm64.tar.gz"
      sha256 "c2072423ac7ec93b0a61fd03161f6be11df8578853edfddb3fae97485e1a9a6b"

      define_method(:install) do
        bin.install "repo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/repo/releases/download/v0.1.0/repo_0.1.0_linux_amd64.tar.gz"
      sha256 "7591f82ca3ea8f08bd2861bfeb872690de4ba4cac6bb994a77276347a6b994a7"
      define_method(:install) do
        bin.install "repo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/repo/releases/download/v0.1.0/repo_0.1.0_linux_arm64.tar.gz"
      sha256 "84356b572296288baaf399af7f7a86d21c4e465b6450563561e4a54d0f09ff72"
      define_method(:install) do
        bin.install "repo"
      end
    end
  end

  test do
    system "#{bin}/repo", "version"
  end
end
