# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ToonCli < Formula
  desc "Stdin/stdout JSON/YAML ⇄ TOON converter."
  homepage "https://github.com/jedi-knights/toon-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jedi-knights/toon-cli/releases/download/v0.1.0/toon-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "1875fa412c5e0c3141b8b30f810d5f02286a102750eb5f78616c7095168cdd91"

      define_method(:install) do
        bin.install "toon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jedi-knights/toon-cli/releases/download/v0.1.0/toon-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "d19aae08a7a26dc5df2c1c2f79f18694955260252ab2ec3a942d908aa57f70fc"

      define_method(:install) do
        bin.install "toon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/toon-cli/releases/download/v0.1.0/toon-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "f23b3d923f238cacaba730688af8ed2629c2f6fa2605468bacf24153ba3186a9"
      define_method(:install) do
        bin.install "toon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jedi-knights/toon-cli/releases/download/v0.1.0/toon-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "c4bebf070304464e14475928248b576699c47c134cc04f351bfd3a650896a9c7"
      define_method(:install) do
        bin.install "toon"
      end
    end
  end

  test do
    system "#{bin}/toon", "--version"
  end
end
